---
abstract: 'Structured version objects'
author:
  - 'John Peacock <jpeacock@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0.13'
  Test::More: '0.45'
  base: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: version
no_index:
  directory:
    - t
    - inc
  package:
    - charstar
requires:
  perl: '5.006002'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=version
  repository: git://github.com/Perl/version.pm.git
version: '0.9930'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
